remote_theme: "mmistakes/minimal-mistakes@4.24.0"
title: zowayix.github.io
description: Megan (Zowayix)'s projects and blogs etc
footer-links:
  twitter: catgirl_megan
collections:
  posts:
    permalink: /blog/:categories/:slug

defaults:
  -
    scope:
      path: "game-reviews"
    values:
      layout: "game-review"
