theme: jekyll-theme-cayman
title: zowayix.github.io
description: Megan (Zowayix)'s projects and blogs etc
footer-links:
  twitter: catgirl_megan
collections:
  posts:
    permalink: /blog/:categories/:slug
twitter_username: catgirl_megan
github_username:  zowayix
markdown: kramdown
plugins:
  - jekyll-feed
defaults:
  -
    scope:
      path: "game-reviews"
    values:
      layout: "game-review"

#email: your-email@example.com
#description: >- # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
