lang: en_AU
title: Megan's Generically Named Site
tagline: Game reviews etc
description: Blog posts inc game reviews and also links to other stuff
footer-links:
  twitter: miss_inputs
collections:
  posts:
    permalink: /blog/:categories/:slug
author:
  name: Megan
  twitter: miss_inputs
twitter:
  miss_inputs
#How many times am I putting my own Twitter handle in here? Oh well
twitter_username: miss_inputs
github_username:  Miss-Inputs
markdown: kramdown
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-seo-tag
defaults:
  -
    scope:
      path: "game-reviews"
    values:
      layout: "game-review"
strict_front_matter: true
social:
  name: Miss Inputs
  links:
    - https://twitter.com/miss_inputs
    - https://github.com/Miss-Inputs
    - https://twitch.tv/miss_inputs
    - https://howlongtobeat.com/user/Zowayix
google_site_verification: DmfSQRPYQfy_sAN5a_flgKABPoOXT0fsfkGRSbN9-Zg
feed:
  categories:
    - game-reviews
remote_theme: allejo/jekyll-docs-theme@v1.0.0
disqus: false
#email: your-email@example.com
#description: >- # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
