theme: jekyll-theme-slate
description: Megan (Zowayix)'s stuff and things
footer-links:
  twitter: catgirl_megan
collections:
  posts:
    permalink: /blog/:categories/:slug

defaults:
  -
    scope:
      path: "game-reviews"
    values:
      layout: "game-review"
